spring:
  application:
    name: ufms
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # redis 配置
  redis:
    # 地址
    host: 47.100.91.123
    # 端口，默认为6379
    port: 6379
    # 密码
    password: ${REDIS_PWD}
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  #thymeleaf模板配置
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    #严格执行H5标准
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  #content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

server:
  servlet:
    context-path: /
  ssl:
    key-store: classpath:server.jks
    key-store-password: Cbgw1udy
    key-store-type: JKS
    protocol: TLS
  port: 1116
