spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LOCAL_HOST}:${MYSQL_PORT}/ufms_dev?useTimezone=true&serverTimezone=GMT%2B8
    username: ${MYSQL_NAME}
    password: ${MYSQL_PWD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: info
    top.ordinaryroad.ufms: debug
  file:
    name: ufms_dev.log
